"""Reviewable lifecycle, inspired by the source project's protected workflow."""

STAGES = [
    {"id": "frame", "title": "Frame the research", "description": "Define the question, scope and human decisions before collecting evidence.", "checks": ["Research question and intended audience recorded", "Assumptions, uncertainty and decision owner recorded"], "kinds": ["decision", "note"]},
    {"id": "inventory", "title": "Inventory all evidence", "description": "Register available, missing, excluded and negative material with its rights and authority.", "checks": ["Sources and datasets registered with origin and rights", "Missing, unused and negative evidence explicitly recorded"], "kinds": ["source", "dataset"]},
    {"id": "methods", "title": "Register materials and protocols", "description": "Link versioned methods to datasets. Mark unknown details rather than filling them in.", "checks": ["Materials and protocol versions recorded", "Dataset-to-material and protocol links checked"], "kinds": ["material", "protocol"]},
    {"id": "corpus", "title": "Read and map the literature", "description": "Distinguish published evidence, author intent and project observations. Use exact locators.", "checks": ["Relevant source passages checked against originals", "Supporting, conflicting and absent evidence mapped"], "kinds": ["source", "claim"]},
    {"id": "terms", "title": "Build the terminology dictionary", "description": "Record preferred terms, aliases, definitions, scope and source support.", "checks": ["Preferred terminology and aliases reviewed", "Definitions and their evidence sources linked"], "kinds": ["term"]},
    {"id": "design", "title": "Prespecify analyses and experiments", "description": "Choose independent units, controls, outcomes and exclusions before looking at results.", "checks": ["Independent units, controls and hypotheses recorded", "Metrics, splits, exclusions and failure criteria frozen"], "kinds": ["experiment", "decision"]},
    {"id": "analyze", "title": "Analyze and preserve provenance", "description": "Keep parameters, input revisions, uncertainty and code versions with each result.", "checks": ["Analysis inputs, parameters and software pinned", "Missingness, uncertainty and all exclusions reported"], "kinds": ["analysis", "processed_data", "software"]},
    {"id": "audit", "title": "Audit bias and claim support", "description": "Check leakage, confounding, pseudoreplication and unsupported interpretations. Screening flags need judgement.", "checks": ["Independence, controls and conflicting evidence examined", "Claims and limitations checked by a named reviewer"], "kinds": ["claim", "decision"]},
    {"id": "synthesis", "title": "Synthesize comparable studies", "description": "Pool only defensibly comparable, independent study estimates. Preserve search and selection criteria.", "checks": ["Eligibility, search scope and study dependencies recorded", "Effect scales, uncertainty and heterogeneity reviewed"], "kinds": ["analysis", "source"]},
    {"id": "story", "title": "Plan the article and journal shortlist", "description": "Let supported results determine the structure. Verify current journal scope and submission requirements.", "checks": ["Article structure follows supported claims", "Journal requirements checked against current official sources"], "kinds": ["manuscript", "decision"]},
    {"id": "figures", "title": "Make reproducible figures", "description": "Link each panel to data, code and analysis. Review labels, scale, units and exclusions.", "checks": ["Figure lineage and numerical values checked", "Legends, units and accessible labels reviewed"], "kinds": ["output"]},
    {"id": "write", "title": "Draft and revise with evidence", "description": "Use a clear scientific voice. Mark unknowns and preserve the distinction between results and interpretation.", "checks": ["Claims and citations checked against source passages", "Style, authorship and unresolved placeholders reviewed"], "kinds": ["manuscript", "claim"]},
    {"id": "release", "title": "Assemble the research handoff", "description": "Inspect the exact article, data and software package before any human-led release.", "checks": ["Rights, privacy, authorship and reproducibility reviewed", "Exact data, software commits and output hashes recorded"], "kinds": ["software", "output", "decision"]},
    {"id": "revision", "title": "Respond to peer review", "description": "Preserve the submitted version, map each request, and revisit only the stages needed.", "checks": ["Exact submission and reviewer requests preserved", "Each response linked to revisions or justified limitations"], "kinds": ["decision", "manuscript"]},
]
